### ISSUE TITLE
3.6.3 ModularPowersuits Causing Clients to force close

### ISSUE THREAD

**Issue by ValdinH** [Haggle1996/RevolutionPack#631]
There seems to be an issue with 3.6.3 and ModularPowersuits. When I updated to 3.6.3 this morning clients were getting a "internal exception: java.io.ioexception: an existing connection was forcibly closed by remote", which seems to be caused by:

Caused by: java.lang.NoClassDefFoundError: net/machinemuse/numina/sound/Musique

Upon disabling this mod and restarting my server clients were again able to join the server. The server as a whole is only about 3 weeks old and no one had any items from this mod in their inventory. Just to verify, i re-enabled ModularPowersuits and restarted the server and clients were once again unable to connect to the server.

**Comment by Haggle1996** [comment]
3.6.4 is on the launcher, which should address this issue.

**Comment by ValdinH** [comment]
Still having the same issue with 3.6.4

Clients are only able to connect to the server if ModularPowersuits is disabled.

**Comment by Haggle1996** [comment]
Have you tried reinstalling both clients and servers, and verifying both clients and server have the same mod list (minus server and client only mods)? I can't replicate this on my setup, but the error you described happens when there's mismatched mods.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ValdinH** [comment]
Started a brand new server and installed a fresh instance of the client on the launcher. Still having the issue with a fresh server and world. I will jsut leave it disabled for now I guess

**Comment by Haggle1996** [comment]
I've reverted MPS to the version in 3.6.2 and released 3.6.5 on the launcher.
